#!/bin/sh

# Assumptions:
# - You used `taman` to extract your students' submissions to `subs/`.
# - You have your solution in `sol/`.
# - You have test files in `test/` (if applicable).

# TODO:
# - Output a grade file for each student.
# - Move each student's solution to their own directory.
# - Implement a character difference tolerance
# - Fix Valgrind output

dir=$PWD
assignment=""
cases=""

[ -f "$dir/tests.sh" ] || {
    cat <<EOF
tests.sh not found.
Create a tests.sh file of the form:
assignment="assignment name"

cases="
commands for test cases
...
"
EOF
    exit 1
}
# shellcheck disable=1091
. "$dir/tests.sh"

IFS='
'
for sub in "$dir/subs/"*; do
    student=$(basename "$sub")
    echo "Grading $student"
    # Copy over files for setting up the environment
    # ex: - Directories and files for pfind
    #     - Header files
    for t in "$dir/test/"*; do
        ln -sf "$t" "$sub/"
        ln -sf "$t" "$dir/sol/"
    done
    cd "$sub" || exit 1
    make || {
        echo "$student $assignment grade: 0: Failed compilation"
        cd "$dir" || exit 1
        echo "Would you like to grade another student? [y/n]"
        read -r continue
        [ "$continue" = "y" ] || break
    }
    make clean || echo "Make clean failed"
    make

    valgrind_errors=0
    right=0
    total=0
    for c in $cases; do
        echo "Test case: $c"
        cd "$dir/sol" || exit 1
        eval "$c" 1>/tmp/taman_stdout_sol 2>/tmp/taman_stderr_sol
        echo $? >/tmp/taman_status_sol
        cd "$sub" || exit 1
        eval "$c" 1>/tmp/taman_stdout_test 2>/tmp/taman_stderr_test
        echo $? >/tmp/taman_status_test
        # TODO: Need to split $c into array of strings
        valgrind -s --leak-check=full --show-leak-kinds=all --track-fds=all \
            --error-exitcode=65 $c 1>/dev/null 2>/dev/null
        [ $? -eq 65 ] && valgrind_errors=$((valgrind_errors + 1))

        diff -y --color /tmp/taman_stdout* && right=$((right + 1))
        diff -y --color /tmp/taman_stderr* && right=$((right + 1))
        diff -y --color /tmp/taman_status* && right=$((right + 1))
        total=$((total + 3))
        rm /tmp/taman_*
        echo
    done

    echo "$student $assignment grade: $right/$total"
    echo "Cases with memory leaks: $valgrind_errors"
    echo
    cd "$dir" || exit 1
    echo "Would you like to grade another student? [y/n]"
    read -r continue
    [ "$continue" = "y" ] || break
done
